export const DATA = [
    {
        alt_description: "Every little helps",
        color: "#000000",
        created_at: "2020-05-06T11:38:25-04:00",
        description: "Donations come from the heart. Our goal here was to let people know that every donation, be it ever so small, can help. No matter if they donate to small businesses, restaurants or local stores in their neighborhood – it all matters. Image created by Loved GmbH. Submitted for United Nations Global Call Out To Creatives - help stop the spread of COVID-19.",
        height: 4961,
        id: "1",
        liked_by_user: false,
        links: {
            download: "https://unsplash.com/photos/QVNyCllG2GQ/download",
            download_location: "https://api.unsplash.com/photos/QVNyCllG2GQ/download",
            html: "https://unsplash.com/photos/QVNyCllG2GQ",
            self: "https://api.unsplash.com/photos/QVNyCllG2GQ"
        },
        accepted_tos: true,
        bio: "To educate, uplift, and inspire people all across the world through the global COVID pandemic crisis, this library of artwork was donated by creators in response to the UN’s Open Brief thanks to the generosity of the creative community.",
        first_name: "United Nations",
        instagram_username: "unitednations",
        last_name: "COVID-19 Response",
        link: {
            followers: "https://api.unsplash.com/users/unitednations/followers"
        },
        following: "https://api.unsplash.com/users/unitednations/following", html: "https://unsplash.com/@unitednations", likes: "https://api.unsplash.com/users/unitednations/likes", photos: "https://api.unsplash.com/users/unitednations/photos",
        name: "United Nations COVID-19 Response",
        portfolio_url: "https://unitednations.talenthouse.com/",
        profile_image: "https://images.unsplash.com/profile-1588813462016-9062fbdc756cimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
        total_collections: 6,
        total_likes: 0,
        total_photos: 114,
        twitter_username: "un",
        updated_at: new Date().toJSON(),
        username: "unitednations",
        width: 3508
    },

    {
        alt_description: "Every little helps",
        color: "#000000",
        created_at: "2020-05-06T11:38:25-04:00",
        description: "Donations come from the heart. Our goal here was to let people know that every donation, be it ever so small, can help. No matter if they donate to small businesses, restaurants or local stores in their neighborhood – it all matters. Image created by Loved GmbH. Submitted for United Nations Global Call Out To Creatives - help stop the spread of COVID-19.",
        height: 4961,
        id: "2",
        liked_by_user: true,
        likes: 61,
        links: {
            download: "https://unsplash.com/photos/QVNyCllG2GQ/download",
            download_location: "https://api.unsplash.com/photos/QVNyCllG2GQ/download",
            html: "https://unsplash.com/photos/QVNyCllG2GQ",
            self: "https://api.unsplash.com/photos/QVNyCllG2GQ"
        },
        accepted_tos: true,
        first_name: "Michael",
        instagram_username: "mdisc",
        last_name: "Discenza",
        link: {
            followers: "https://api.unsplash.com/users/mdisc/followers",
            following: "https://api.unsplash.com/users/mdisc/following",
            html: "https://unsplash.com/@mdisc",
            likes: "https://api.unsplash.com/users/mdisc/likes",
            photos: "https://api.unsplash.com/users/mdisc/photos",
            portfolio: "https://api.unsplash.com/users/mdisc/portfolio",
            self: "https://api.unsplash.com/users/mdisc"
        },
        location: "Austin, TX",
        name: "Michael Discenza",
        portfolio_url: "http://photo.mdiscenza.com",
        profile_image: "https://images.unsplash.com/profile-fb-1456184697-467e46e57ac3.jpg?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
        total_collections: 6,
        total_likes: 0,
        total_photos: 114,
        twitter_username: "un",
        updated_at: new Date().toJSON(),
        username: "unitednations",
        width: 3508
    },
    {
        alt_description: "person in brown long sleeve shirt raising both hands",
        color: "#78351F",
        created_at: "2020-05-16T04:27:03-04:00",
        description: "\"THE HAND\" \nTHE BEGINNING of a huge project",
        height: 3168,
        id: "3",
        liked_by_user: true,
        likes: 23,
        links: {
            download: "https://unsplash.com/photos/z1MMCxNJRiA/download",
            download_location: "https://api.unsplash.com/photos/z1MMCxNJRiA/download",
            html: "https://unsplash.com/photos/z1MMCxNJRiA",
            self: "https://api.unsplash.com/photos/z1MMCxNJRiA",
        },
        accepted_tos: true,
        first_name: "Hans",
        instagram_username: "hans_veth",
        last_name: "Veth",
        link: {
            followers: "https://api.unsplash.com/users/hans_veth/followers",
            following: "https://api.unsplash.com/users/hans_veth/following",
            html: "https://unsplash.com/@hans_veth",
            likes: "https://api.unsplash.com/users/hans_veth/likes",
            photos: "https://api.unsplash.com/users/hans_veth/photos",
            portfolio: "https://api.unsplash.com/users/hans_veth/portfolio",
            self: "https://api.unsplash.com/users/hans_veth"
        },
        name: "Michael Discenza",
        portfolio_url: "http://photo.mdiscenza.com",
        profile_image: "https://images.unsplash.com/profile-1571077135816-5c640e5080fbimage?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
        total_collections: 7,
        total_likes: 94,
        total_photos: 180,
        twitter_username: "un",
        updated_at: new Date().toJSON(),
        username: "hans_veth",
        width: 4301
    },
];
